name: Build Package

on:
  workflow_call:  # Makes this workflow reusable
    inputs:
      python-versions:
        description: "Python versions to test"
        required: true
        type: string
      os-matrix:
        description: "Operating systems to test"
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os-matrix) }}
        python-version: ${{ fromJson(inputs.python-versions) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build

      - name: Build package
        run: python -m build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-py${{ matrix.python-version }}  # Unique artifact name
          path: dist/